### PR TITLE
remove %caml_string_set16u, use the bytes equivalent

### PR DESCRIPTION
**Pull request by hhugo**
this is in preparation for https://github.com/ocsigen/js_of_ocaml/pull/923

### CODE REVIEW

**Comment by hhugo** [comment]
Note that the patch doesn't work with OCaml < 4,07.

**Comment by dinosaure** [comment]
Thanks, let me think about a compatibility way :+1:

**Comment by hhugo** [comment]
With a light https://github.com/ocsigen/js_of_ocaml/blob/master/compiler/ppx/ppx_optcomp_light.ml
  version of ppx_optcomp

Here is how jsoo does it.
```ocaml
external unsafe_set_uint16 : bytes -> int -> int -> unit = "%caml_string_set16u"
  [@@noalloc] [@@if ocaml_version < (4, 7, 0)]

external unsafe_set_uint16 : bytes -> int -> int -> unit = "%caml_bytes_set16u"
  [@@noalloc] [@@if ocaml_version >= (4, 7, 0)]

```

**Comment by dinosaure** [comment]
Ok, I will try to propose a PR with your commit, thanks!

**Comment by dinosaure** [comment]
Close by #37.

**Pull request closed without merging**
