### PR TITLE
 Make whitespace handling more permissive

### PR DESCRIPTION
**Pull request by tiash**
While attempting to update [[Async_smtp]](https://www.github.com/janestreet/async_smtp) to use this library we saw issues when parsing emails with non compliant base64 input.

This makes [[Base64_rfc2045]](https://github.com/mirage/ocaml-base64/blob/master/src/base64_rfc2045.mli) ignore any combination of white space characters, including non standard line breaks.

This may also help address #6.

### CODE REVIEW

**Comment by dinosaure** [comment]
Hmmhmm, this PR can have several consequences when we will able to accept _invalid_ bodies. I need to figure out if we really need this. I mean, from my point of view, I mostly prefer to strictly follow RFC 2045 and just leave up if we encounter invalid input (with, obviously, a precise error message).

In my mind, your PR let me two concerns:
- we lost isomorphism [checked by fuzzer](https://github.com/mirage/ocaml-base64/blob/master/fuzz/fuzz_rfc2045.ml#L141) with this PR where the `decoder` will accept more than we can `encode` - so `encode(decode(x)) <> x`.
- accept wrong input give you lot of responsibilities where some post-treatments expect a valid `base64` input according RFC.

I know your concerns about invalid contents where it's a common kind of inputs when we manipulate real-worlds e-mails but you really want to be less paranoid about what you accept and what you should discard?

**Comment by dinosaure** [comment]
And about #6, the task is much more about `Base64` than `Base64_rfc2045`.

**Comment by tiash** [comment]
> * we lost isomorphism [checked by fuzzer](https://github.com/mirage/ocaml-base64/blob/master/fuzz/fuzz_rfc2045.ml#L141) with this PR where the `decoder` will accept more than we can `encode` - so `encode(decode(x)) <> x`.

I don't think this isomorphism held before. The decoder already ignored space and tab characters in most positions.

**Comment by dinosaure** [comment]
You are true, I will investigate all of these next week :+1:

**Comment by avsm** [comment]
I'm ok with accepting invalid bodies and doing a best-effort parse, but it would be fantastic if we could still have a strict mode to distinguish between valid and invalid input with respect to RFC2045.

That would permit MrMime and other stacks to lint incoming email (which is useful for building services such as spam filtering on top of these libraries, where invalid bodies can be weighted as spam)

**Comment by avsm** [comment]
Any reason not to fix this same thing in `Base64` as well? It would be good to get github api support in for blobs as well.

**Comment by dinosaure** [comment]
@tiash if you provide a way (like an optional `paranoid` argument) to be more resilient about kind of inputs - and by this way, keep the current semantic - I will happy to merge your PR 👍 .

**Comment by tiash** [comment]
I agree, exposing if the input is compliant is a useful feature.

Fixing `Malformed to always make forward progress might be enough to make this feature unecessary (and it would open the door to making the parser stricter and still allow permissive clients).
I should have a pull request to fix `Malformed shortly.

**Comment by dinosaure** [comment]
> Any reason not to fix this same thing in Base64 as well? It would be good to get github api support in for blobs as well.

I will make it in a separate PR.

**Comment by hannesm** [comment]
I'd name this optional labeled argument `strict`, and have it `true` by default ;) I'm also interested about performance impact (if set to `true`, i.e. in the default case)

**Comment by tiash** [comment]
I'm closing this pull request as the fixes from #34 make this unecessary: Client code can choose too ignore non standard white space by checking and continuing on `Malformed.

**Pull request closed without merging**
