### PR TITLE
Use %caml_bytes_set16u when it's available (with dune-configurator)

### PR DESCRIPTION
**Pull request by dinosaure**
According #36.

### CODE REVIEW

**Comment by dinosaure** [comment]
Even if it's a light PPX, I don't like to put an other dependence to `base64`, so this PR still exists and if I did not find anything to keep compat', I will probably merge it.

**Comment by avsm** [comment]
For other libraries, we are simply bumping the upper bound (e.g. cstruct-unix is already 4.06+).  Given that the base64 library is not changing rapidly, I'd prefer this to simply be upper bounded to 4.07+ and keep the complexity down.

I can be convinced otherwise if you feel strongly that you do want this ppx and multiversion support PR merged, however :-)

**Comment by dinosaure** [comment]
My concerns is mostly about external projects of MirageOS where some people use `base64`. I discovered it when I broke compat' and renamed `B64` to `Base64` :( .

**Comment by dinosaure** [comment]
Hmmhmm, I think that we can use another mechanism with `dune-configurator` instead to use a PPX. I will try to find a solution today.

**Comment by dinosaure** [comment]
I think it's a good solution and it's work for `< 4.07` and `>= 4.07`. Merge!

**Pull request merged**
